name: CI

on:
  push:
    branches:
      - "**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install just prettier
      - run: just check

  deploy-site:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    # Permissions necessary for ${{ secrets.GITHUB_TOKEN }}
    # to allow cloudflare/pages-action to create deployment:
    # https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_EDIT_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: compute-fornwall-net
          directory: .
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
